name: "Setup & Run YDB"
description: "Sets up YDB test environment with monitoring. Collects and uploads metrics during cleanup."

inputs:
  github_issue:
    description: "The number of the associated pull request. If not provided, the action will attempt to infer it automatically."
    required: false
  github_token:
    description: "GitHub token used to access the GitHub API for inferring the pull request number."
    required: false
  workload_name:
    description: "The name of the workload used by the user to generate load on the YDB database."
    required: true
  workload_current_ref:
    description: "The current ref/branch name being tested (e.g., PR branch name). This will be used to identify current metrics."
    required: true
  workload_baseline_ref:
    description: "The baseline ref/branch name used for comparison (e.g., 'main', 'master'). This will be used to identify base metrics."
    required: true
  metrics_yaml:
    description: "Custom metrics configuration in YAML format (inline). Will be merged with default metrics."
    required: false
  metrics_yaml_path:
    description: "Path to a file containing custom metrics configuration in YAML format. Will be merged with default metrics."
    required: false
  disable_compose_profiles:
    description: "Comma-separated list of compose profiles to disable (e.g., 'chaos,telemetry'). By default, all profiles are enabled."
    required: false

outputs:
  ydb-storage-ips:
    description: "Comma-separated list of YDB storage node IP addresses."
  ydb-database-ips:
    description: "Comma-separated list of YDB databse node IP addresses."
  ydb-prometheus-url:
    description: "The prometheus url if telemetry profile is not disabled."

runs:
  using: "node24"
  main: "../dist/init/main.js"
  post: "../dist/init/post.js"
