name: "Setup & Run YDB"
description: "Sets up YDB test environment with monitoring. Collects and uploads metrics during cleanup."

inputs:
  github_pull_request_number:
    description: "The number of the associated pull request. If not provided, the action will attempt to infer it automatically."
    required: false
  github_token:
    description: "GitHub token used to access the GitHub API for inferring the pull request number."
    required: false
  workload_name:
    description: "The name of the workload used by the user to generate load on the YDB database."
    required: true
  metrics_yaml:
    description: "Custom metrics configuration in YAML format (inline). Will be merged with default metrics."
    required: false
  metrics_yaml_path:
    description: "Path to a file containing custom metrics configuration in YAML format. Will be merged with default metrics."
    required: false

runs:
  using: "node24"
  main: "../dist/init/main.js"
  post: "../dist/init/post.js"
