/**
 * PR comment generation and management for report2
 */

import { debug, getInput, info } from '@actions/core'
import { context, getOctokit } from '@actions/github'

export interface WorkloadReportSummary {
	workload: string
	currentRef: string
	baselineRef: string
	metricsCount: number
	reportUrl?: string
	evaluation?: {
		overall: 'success' | 'warning' | 'failure'
		failures: Array<{ name: string; reason?: string }>
		warnings: Array<{ name: string; reason?: string }>
	}
}

/**
 * Generate PR comment body for all workloads
 */
export function generateCommentBody(reports: WorkloadReportSummary[]): string {
	let totalFailures = reports.filter((r) => r.evaluation?.overall === 'failure').length
	let totalWarnings = reports.filter((r) => r.evaluation?.overall === 'warning').length

	let statusEmoji = totalFailures > 0 ? '🔴' : totalWarnings > 0 ? '🟡' : '🟢'
	let statusText =
		totalFailures > 0
			? `${totalFailures} workload(s) failed`
			: totalWarnings > 0
				? `${totalWarnings} workload(s) with warnings`
				: 'All passed'

	let header = `## 🌋 SLO Test Results

**Status:** ${statusEmoji} ${reports.length} workload(s) tested • ${statusText}

`

	let rows = reports.map((report) => {
		let emoji =
			report.evaluation?.overall === 'failure'
				? '🔴'
				: report.evaluation?.overall === 'warning'
					? '🟡'
					: '🟢'

		let thresholdInfo = ''
		if (report.evaluation?.failures.length) {
			thresholdInfo = ` (${report.evaluation.failures.length} critical)`
		} else if (report.evaluation?.warnings.length) {
			thresholdInfo = ` (${report.evaluation.warnings.length} warnings)`
		}

		let reportLink = report.reportUrl ? `[📄 Report](${report.reportUrl})` : '-'

		return `| ${emoji} | **${report.workload}** | \`${report.currentRef}\` | \`${report.baselineRef}\` | ${report.metricsCount}${thresholdInfo} | ${reportLink} |`
	})

	let table = `| | Workload | Current | Baseline | Metrics | Report |
|---|----------|---------|----------|---------|--------|
${rows.join('\n')}
`

	let footer = `
---
_Generated by [ydb-slo-action](https://github.com/ydb-platform/ydb-slo-action)_`

	return header + table + footer
}

/**
 * Find existing SLO comment in PR
 */
async function findExistingComment(pull: number): Promise<number | null> {
	let token = getInput('github_token')
	let octokit = getOctokit(token)

	debug(`Searching for existing SLO comment in PR #${pull}`)

	let { data: comments } = await octokit.rest.issues.listComments({
		issue_number: pull,
		owner: context.repo.owner,
		repo: context.repo.repo,
	})

	for (let comment of comments) {
		if (comment.body?.includes('🌋 SLO Test Results')) {
			debug(`Found existing comment: ${comment.id}`)
			return comment.id
		}
	}

	return null
}

/**
 * Create or update PR comment
 */
export async function createOrUpdateComment(pull: number, body: string): Promise<{ url: string; id: number }> {
	let token = getInput('github_token')
	let octokit = getOctokit(token)

	let existingId = await findExistingComment(pull)

	if (existingId) {
		info(`Updating existing comment ${existingId}`)

		let { data } = await octokit.rest.issues.updateComment({
			comment_id: existingId,
			owner: context.repo.owner,
			repo: context.repo.repo,
			body,
		})

		return { url: data.html_url!, id: data.id }
	}

	info(`Creating new comment`)

	let { data } = await octokit.rest.issues.createComment({
		issue_number: pull,
		owner: context.repo.owner,
		repo: context.repo.repo,
		body,
	})

	return { url: data.html_url!, id: data.id }
}
