/**
 * PR comment generation and management
 */

import { debug, getInput, info } from '@actions/core'
import { context, getOctokit } from '@actions/github'

import {
	formatValue,
	type MetricAnalysis,
	type Severity,
	type WorkloadAnalysis,
} from '../../shared/analysis.js'
export interface WorkloadReportSummary {
	workload: string
	currentRef: string
	baselineRef: string
	reportUrl?: string
	analysis: WorkloadAnalysis
}

/**
 * Render a 40-char wide ASCII box plot for two distributions
 */
function renderAsciiBoxPlot(
	currentBox: [number, number, number, number, number],
	baselineBox: [number, number, number, number, number],
	currentLabel: string,
	baselineLabel: string
): string {
	let allValues = [...currentBox, ...baselineBox].filter((v) => isFinite(v))
	if (allValues.length === 0) return ''

	let min = Math.min(...allValues)
	let max = Math.max(...allValues)
	if (min === max) return ''

	let width = 40
	let scale = (v: number) => Math.round(((v - min) / (max - min)) * (width - 1))

	function renderBox(box: [number, number, number, number, number]): string {
		let [bMin, q1, med, q3, bMax] = box.map(scale)
		let line = new Array(width).fill(' ')

		// Whiskers
		for (let i = bMin; i <= bMax; i++) line[i] = '-'
		// Box
		for (let i = q1; i <= q3; i++) line[i] = '='
		// Fences
		line[bMin] = '|'
		line[bMax] = '|'
		line[q1] = '['
		line[q3] = ']'
		// Median
		line[med] = '|'

		return line.join('')
	}

	let padLen = Math.max(currentLabel.length, baselineLabel.length)
	let cPad = currentLabel.padEnd(padLen)
	let bPad = baselineLabel.padEnd(padLen)

	return `${cPad}: ${renderBox(currentBox)}\n${bPad}: ${renderBox(baselineBox)}`
}

/**
 * Status emoji for severity
 */
function severityEmoji(severity: Severity): string {
	return severity === 'failure' ? '🔴' : severity === 'warning' ? '🟡' : '🟢'
}

/**
 * Metric status emoji (more granular for the table)
 */
function metricStatusEmoji(metric: MetricAnalysis): string {
	if (metric.severity === 'failure') return '🔴'
	if (metric.severity === 'warning') return '🟡'
	if (metric.relativeCheck) {
		let abs = Math.abs(metric.relativeCheck.changePercent)
		if (abs < 5) return '⚪'
	}
	return '✅'
}

/**
 * Generate PR comment body for all workloads
 */
export function generateCommentBody(reports: WorkloadReportSummary[]): string {
	let totalFailures = reports.filter((r) => r.analysis.severity === 'failure').length
	let totalWarnings = reports.filter((r) => r.analysis.severity === 'warning').length

	let statusEmoji = totalFailures > 0 ? '🔴' : totalWarnings > 0 ? '🟡' : '🟢'
	let statusText =
		totalFailures > 0
			? `${totalFailures} workload(s) failed`
			: totalWarnings > 0
				? `${totalWarnings} workload(s) with warnings`
				: 'All passed'

	let lines: string[] = [
		`## 🌋 SLO Test Results`,
		``,
		`**Status:** ${statusEmoji} ${reports.length} workload(s) tested • ${statusText}`,
		``,
	]

	for (let report of reports) {
		let emoji = severityEmoji(report.analysis.severity)
		let reportLink = report.reportUrl ? ` • [📄 Report](${report.reportUrl})` : ''
		lines.push(`### ${report.workload} ${emoji}${reportLink}`)
		lines.push(``)

		// Metrics table
		let hasBaseline = report.analysis.metrics.some((m) => m.relativeCheck)

		if (hasBaseline) {
			lines.push(`| Metric | Current | Baseline | Change | Conc. | Status |`)
			lines.push(`|--------|---------|----------|--------|-------|--------|`)

			for (let m of report.analysis.metrics) {
				let currentVal = formatValue(m.current.trimmedMean, m.name)
				let baselineVal = formatValue(m.baseline.trimmedMean, m.name)
				let change = m.relativeCheck ? `${m.relativeCheck.changePercent >= 0 ? '+' : ''}${m.relativeCheck.changePercent.toFixed(1)}%` : 'N/A'
				let conc = m.relativeCheck ? m.relativeCheck.concordance.toFixed(2) : 'N/A'
				let status = metricStatusEmoji(m)

				lines.push(`| ${m.name} | ${currentVal} | ${baselineVal} | ${change} | ${conc} | ${status} |`)
			}
		} else {
			lines.push(`| Metric | Current | Status |`)
			lines.push(`|--------|---------|--------|`)

			for (let m of report.analysis.metrics) {
				let currentVal = formatValue(m.current.trimmedMean, m.name)
				let status = metricStatusEmoji(m)
				lines.push(`| ${m.name} | ${currentVal} | ${status} |`)
			}
		}

		lines.push(``)

		// Box plots in details section
		let boxPlotMetrics = report.analysis.metrics.filter((m) => m.visualization)
		if (boxPlotMetrics.length > 0) {
			lines.push(`<details>`)
			lines.push(`<summary>Box plots</summary>`)
			lines.push(``)
			lines.push('```')

			for (let m of boxPlotMetrics) {
				let viz = m.visualization!
				lines.push(m.name)
				let plot = renderAsciiBoxPlot(
					viz.currentBox,
					viz.baselineBox,
					'current',
					'baseline'
				)
				if (plot) {
					lines.push(`  ${plot.split('\n').join('\n  ')}`)
				}
				lines.push(``)
			}

			lines.push('```')
			lines.push(`</details>`)
			lines.push(``)
		}
	}

	lines.push(`---`)
	lines.push(`_Generated by [ydb-slo-action](https://github.com/ydb-platform/ydb-slo-action)_`)

	return lines.join('\n')
}

/**
 * Find existing SLO comment in PR
 */
async function findExistingComment(pull: number): Promise<number | null> {
	let token = getInput('github_token')
	let octokit = getOctokit(token)

	debug(`Searching for existing SLO comment in PR #${pull}`)

	let { data: comments } = await octokit.rest.issues.listComments({
		issue_number: pull,
		owner: context.repo.owner,
		repo: context.repo.repo,
	})

	for (let comment of comments) {
		if (comment.body?.includes('🌋 SLO Test Results')) {
			debug(`Found existing comment: ${comment.id}`)
			return comment.id
		}
	}

	return null
}

/**
 * Create or update PR comment
 */
export async function createOrUpdateComment(pull: number, body: string): Promise<{ url: string; id: number }> {
	let token = getInput('github_token')
	let octokit = getOctokit(token)

	let existingId = await findExistingComment(pull)

	if (existingId) {
		info(`Updating existing comment ${existingId}`)

		let { data } = await octokit.rest.issues.updateComment({
			comment_id: existingId,
			owner: context.repo.owner,
			repo: context.repo.repo,
			body,
		})

		return { url: data.html_url!, id: data.id }
	}

	info(`Creating new comment`)

	let { data } = await octokit.rest.issues.createComment({
		issue_number: pull,
		owner: context.repo.owner,
		repo: context.repo.repo,
		body,
	})

	return { url: data.html_url!, id: data.id }
}
