/**
 * PR comment generation and management
 */

import { debug, getInput, info } from '@actions/core'
import { context, getOctokit } from '@actions/github'

import { type Severity, type WorkloadAnalysis } from '../../shared/analysis.js'
export interface WorkloadReportSummary {
	failed: boolean
	workload: string
	currentRef: string
	baselineRef: string
	reportUrl?: string
	analysis: WorkloadAnalysis
	commit?: string
	repoUrl?: string
	runUrl?: string
	durationMs?: number
}

/**
 * Threshold status emoji for severity
 */
function severityEmoji(severity: Severity): string {
	return severity === 'failure' ? '🔴' : severity === 'warning' ? '🟡' : '🟢'
}

/**
 * Collect all threshold violation reasons from a workload analysis
 */
function collectViolations(analysis: WorkloadAnalysis): Array<{ metric: string; reason: string }> {
	let result: Array<{ metric: string; reason: string }> = []

	for (let m of analysis.metrics) {
		for (let v of m.absoluteCheck.violations) {
			result.push({ metric: m.name, reason: v })
		}
		for (let v of m.relativeCheck?.violations ?? []) {
			result.push({ metric: m.name, reason: v })
		}
		if (m.retriesCheck?.reason && m.retriesCheck.severity !== 'success') {
			result.push({ metric: m.name, reason: m.retriesCheck.reason })
		}
	}

	return result
}

/**
 * Format milliseconds as human-readable duration (e.g. "5m 30s")
 */
function formatDuration(ms: number): string {
	let totalSeconds = Math.round(ms / 1000)
	let minutes = Math.floor(totalSeconds / 60)
	let seconds = totalSeconds % 60
	if (minutes === 0) return `${seconds}s`
	if (seconds === 0) return `${minutes}m`
	return `${minutes}m ${seconds}s`
}

/**
 * Generate PR comment body for all workloads
 */
export function generateCommentBody(reports: WorkloadReportSummary[]): string {
	let totalFailures = reports.filter((r) => r.analysis.severity === 'failure').length
	let totalWarnings = reports.filter((r) => r.analysis.severity === 'warning').length

	let overallEmoji = totalFailures > 0 ? '🔴' : totalWarnings > 0 ? '🟡' : '🟢'
	let overallText =
		totalFailures > 0
			? `${totalFailures} workload(s) exceeded failure thresholds`
			: totalWarnings > 0
				? `${totalWarnings} workload(s) exceeded warning thresholds`
				: 'All thresholds passed'

	// Build commit/run info line from first report that has the data
	let first = reports[0]
	let metaParts: string[] = []
	if (first?.commit && first?.repoUrl) {
		let short = first.commit.slice(0, 7)
		metaParts.push(`**Commit:** [\`${short}\`](${first.repoUrl}/commit/${first.commit})`)
	} else if (first?.commit) {
		metaParts.push(`**Commit:** \`${first.commit.slice(0, 7)}\``)
	}
	if (first?.runUrl) {
		metaParts.push(`[View run](${first.runUrl})`)
	}

	let lines: string[] = [
		`## 🌋 SLO Test Results`,
		``,
		`${overallEmoji} ${reports.length} workload(s) tested — ${overallText}`,
	]

	if (metaParts.length > 0) {
		lines.push(``)
		lines.push(metaParts.join(' · '))
	}

	lines.push(``)
	lines.push(`| Workload | Thresholds | Duration | Report |`)
	lines.push(`|----------|:----------:|:--------:|--------|`)

	for (let report of reports) {
		let emoji = severityEmoji(report.analysis.severity)
		let thresholdLabel =
			report.analysis.severity === 'failure'
				? `${emoji} Failure`
				: report.analysis.severity === 'warning'
					? `${emoji} Warning`
					: `${emoji} OK`
		let durationCell = report.durationMs != null ? formatDuration(report.durationMs) : '—'
		let reportCell = report.reportUrl ? `[📄 Report](${report.reportUrl})` : '—'
		lines.push(`| ${report.workload} | ${thresholdLabel} | ${durationCell} | ${reportCell} |`)
	}

	// Threshold violations section
	let violatingReports = reports.filter((r) => r.analysis.severity !== 'success')
	if (violatingReports.length > 0) {
		lines.push(``)
		lines.push(`**Threshold violations:**`)

		for (let report of violatingReports) {
			let violations = collectViolations(report.analysis)
			if (violations.length === 0) continue

			lines.push(``)
			lines.push(`**${report.workload}:**`)
			for (let { metric, reason } of violations) {
				lines.push(`- \`${metric}\`: ${reason}`)
			}
		}
	}

	lines.push(``)
	lines.push(`---`)
	lines.push(`_Generated by [ydb-slo-action](https://github.com/ydb-platform/ydb-slo-action)_`)

	return lines.join('\n')
}

/**
 * Find existing SLO comment in PR
 */
async function findExistingComment(pull: number): Promise<number | null> {
	let token = getInput('github_token')
	let octokit = getOctokit(token)

	debug(`Searching for existing SLO comment in PR #${pull}`)

	let { data: comments } = await octokit.rest.issues.listComments({
		issue_number: pull,
		owner: context.repo.owner,
		repo: context.repo.repo,
	})

	for (let comment of comments) {
		if (comment.body?.includes('🌋 SLO Test Results')) {
			debug(`Found existing comment: ${comment.id}`)
			return comment.id
		}
	}

	return null
}

/**
 * Create or update PR comment
 */
export async function createOrUpdateComment(
	pull: number,
	body: string
): Promise<{ url: string; id: number }> {
	let token = getInput('github_token')
	let octokit = getOctokit(token)

	let existingId = await findExistingComment(pull)

	if (existingId) {
		info(`Deleting existing comment ${existingId} and re-creating to keep it at the bottom`)

		await octokit.rest.issues.deleteComment({
			comment_id: existingId,
			owner: context.repo.owner,
			repo: context.repo.repo,
		})
	}

	info(`Creating new comment`)

	let { data } = await octokit.rest.issues.createComment({
		issue_number: pull,
		owner: context.repo.owner,
		repo: context.repo.repo,
		body,
	})

	return { url: data.html_url!, id: data.id }
}
