/**
 * GitHub PR comment generation and management
 */

import { info } from '@actions/core'
import { getOctokit } from '@actions/github'

import type { WorkloadComparison } from './analysis.js'

export interface CommentData {
	workloads: WorkloadComparison[]
	artifactUrls: Map<string, string>
	checkUrls: Map<string, string>
	jobSummaryUrl?: string
}

/**
 * Generate PR comment body
 */
export function generateCommentBody(data: CommentData): string {
	let totalRegressions = data.workloads.reduce((sum, w) => sum + w.summary.regressions, 0)
	let totalImprovements = data.workloads.reduce((sum, w) => sum + w.summary.improvements, 0)

	let statusEmoji = totalRegressions > 0 ? '🟡' : '🟢'
	let statusText = totalRegressions > 0 ? `${totalRegressions} regressions` : 'All clear'

	let header = `## 🌋 SLO Test Results

**Status**: ${statusEmoji} ${data.workloads.length} workloads tested • ${statusText}

${data.jobSummaryUrl ? `📈 [View Job Summary](${data.jobSummaryUrl}) for detailed comparison\n` : ''}`

	let table = `
| Workload | Metrics | Regressions | Improvements | Links |
|----------|---------|-------------|--------------|-------|
${data.workloads
	.map((w) => {
		let emoji = w.summary.regressions > 0 ? '🟡' : w.summary.improvements > 0 ? '🟢' : '⚪'
		let reportLink = data.artifactUrls.get(w.workload) || '#'
		let checkLink = data.checkUrls.get(w.workload) || '#'

		return `| ${emoji} ${w.workload} | ${w.summary.total} | ${w.summary.regressions} | ${w.summary.improvements} | [Report](${reportLink}) • [Check](${checkLink}) |`
	})
	.join('\n')}
`

	let footer = `\n---\n*Generated by [ydb-slo-action](https://github.com/ydb-platform/ydb-slo-action)*`

	return header + table + footer
}

/**
 * Find existing SLO comment in PR
 */
export async function findExistingSLOComment(
	token: string,
	owner: string,
	repo: string,
	prNumber: number
): Promise<number | null> {
	let octokit = getOctokit(token)

	info(`Searching for existing SLO comment in PR #${prNumber}...`)

	let { data: comments } = await octokit.rest.issues.listComments({
		owner,
		repo,
		issue_number: prNumber,
	})

	for (let comment of comments) {
		if (comment.body?.includes('🌋 SLO Test Results')) {
			info(`Found existing comment: ${comment.id}`)
			return comment.id
		}
	}

	return null
}

/**
 * Create or update PR comment
 */
export async function createOrUpdateComment(
	token: string,
	owner: string,
	repo: string,
	prNumber: number,
	body: string
): Promise<{ url: string; id: number }> {
	let octokit = getOctokit(token)

	let existingId = await findExistingSLOComment(token, owner, repo, prNumber)

	if (existingId) {
		info(`Updating existing comment ${existingId}...`)

		let { data } = await octokit.rest.issues.updateComment({
			owner,
			repo,
			comment_id: existingId,
			body,
		})

		info(`Comment updated: ${data.html_url}`)

		return { url: data.html_url!, id: data.id }
	} else {
		info(`Creating new comment...`)

		let { data } = await octokit.rest.issues.createComment({
			owner,
			repo,
			issue_number: prNumber,
			body,
		})

		info(`Comment created: ${data.html_url}`)

		return { url: data.html_url!, id: data.id }
	}
}
