/**
 * HTML report generation with Chart.js
 */

import { formatChange, formatValue, type WorkloadComparison } from './analysis.js'
import type { FormattedEvent } from './events.js'
import type { CollectedMetric, MetricsMap, Series } from './metrics.js'

export interface HTMLReportData {
	workload: string
	comparison: WorkloadComparison
	metrics: MetricsMap
	events: FormattedEvent[]
	commits: {
		current: { sha: string; url: string; short: string }
		base: { sha: string; url: string; short: string }
	}
	meta: {
		prNumber: number
		generatedAt: string
		testDuration?: string
	}
}

/**
 * Generate HTML report
 */
export function generateHTMLReport(data: HTMLReportData): string {
	return `<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>SLO Report: ${escapeHtml(data.workload)}</title>
	<style>${getStyles()}</style>
</head>
<body>
	<header>
		<h1>🌋 SLO Report: ${escapeHtml(data.workload)}</h1>
		<div class="commit-info">
			<span class="commit current">
				Current: <a href="${data.commits.current.url}" target="_blank">${data.commits.current.short}</a>
			</span>
			<span class="vs">vs</span>
			<span class="commit base">
				Base: <a href="${data.commits.base.url}" target="_blank">${data.commits.base.short}</a>
			</span>
		</div>
		<div class="meta">
			<span>PR #${data.meta.prNumber}</span>
			${data.meta.testDuration ? `<span>Duration: ${data.meta.testDuration}</span>` : ''}
			<span>Generated: ${data.meta.generatedAt}</span>
		</div>
	</header>

	<section class="summary">
		<h2>📊 Metrics Overview</h2>
		<div class="stats">
			<div class="stat-card">
				<div class="stat-value">${data.comparison.summary.total}</div>
				<div class="stat-label">Total Metrics</div>
			</div>
			<div class="stat-card improvements">
				<div class="stat-value">${data.comparison.summary.improvements}</div>
				<div class="stat-label">Improvements</div>
			</div>
			<div class="stat-card regressions">
				<div class="stat-value">${data.comparison.summary.regressions}</div>
				<div class="stat-label">Regressions</div>
			</div>
			<div class="stat-card stable">
				<div class="stat-value">${data.comparison.summary.stable}</div>
				<div class="stat-label">Stable</div>
			</div>
		</div>
		${generateComparisonTable(data.comparison)}
	</section>

	<section class="charts">
		<h2>📈 Time Series</h2>
		${generateCharts(data)}
	</section>

	${data.events.length > 0 ? generateEventsSection(data.events) : ''}

	<footer>
		<p>Generated by <a href="https://github.com/ydb-platform/ydb-slo-action" target="_blank">ydb-slo-action</a></p>
	</footer>

	<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3.0.0/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@3.0.1/dist/chartjs-plugin-annotation.min.js"></script>
	<script>
		${generateChartScripts(data)}
	</script>
</body>
</html>`
}

function escapeHtml(text: string): string {
	return text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#039;')
}

function generateComparisonTable(comparison: WorkloadComparison): string {
	let rows = comparison.metrics
		.map(
			(m) => `
		<tr class="${m.change.direction}">
			<td>${escapeHtml(m.name)}</td>
			<td>${formatValue(m.current.value, m.name)}</td>
			<td>${m.base.available ? formatValue(m.base.value, m.name) : 'N/A'}</td>
			<td class="change-cell">${m.base.available ? formatChange(m.change.percent, m.change.direction) : 'N/A'}</td>
		</tr>
	`
		)
		.join('')

	return `
		<table class="comparison-table">
			<thead>
				<tr>
					<th>Metric</th>
					<th>Current</th>
					<th>Base</th>
					<th>Change</th>
				</tr>
			</thead>
			<tbody>
				${rows}
			</tbody>
		</table>
	`
}

function generateCharts(data: HTMLReportData): string {
	return data.comparison.metrics
		.filter((m) => m.type === 'range') // Only range metrics have charts
		.map((comparison) => {
			let metric = data.metrics.get(comparison.name)
			if (!metric) return ''

			return `
		<div class="chart-card">
			<div class="chart-header">
				<h3>
					${escapeHtml(comparison.name)}
					<span class="indicator ${comparison.change.direction}">${formatChange(comparison.change.percent, comparison.change.direction)}</span>
				</h3>
				<div class="chart-meta">
					Current: ${formatValue(comparison.current.value, comparison.name)}
					${comparison.base.available ? ` • Base: ${formatValue(comparison.base.value, comparison.name)}` : ''}
				</div>
			</div>
			<div class="chart-container">
				<canvas id="chart-${sanitizeId(comparison.name)}"></canvas>
			</div>
		</div>
	`
		})
		.join('')
}

function generateEventsSection(events: FormattedEvent[]): string {
	let eventsList = events
		.map(
			(e) => `
		<div class="event-item">
			<span class="event-marker" style="background-color: ${e.color}"></span>
			<span class="event-icon">${e.icon}</span>
			<span class="event-time">${formatTimestamp(e.timestamp)}</span>
			<span class="event-label">${escapeHtml(e.label)}</span>
		</div>
	`
		)
		.join('')

	return `
	<section class="events-section">
		<h2>📍 Events Timeline</h2>
		<div class="events-list">
			${eventsList}
		</div>
	</section>
	`
}

function generateChartScripts(data: HTMLReportData): string {
	let chartScripts = data.comparison.metrics
		.filter((m) => m.type === 'range')
		.map((comparison) => {
			let metric = data.metrics.get(comparison.name)
			if (!metric) return ''

			return generateSingleChartScript(comparison.name, metric as CollectedMetric, data.events)
		})
		.join('\n')

	return chartScripts
}

function generateSingleChartScript(metricName: string, metric: CollectedMetric, events: FormattedEvent[]): string {
	let currentSeries = (metric.data as Series[]).find((s) => s.metric.ref === 'current')
	let baseSeries = (metric.data as Series[]).find((s) => s.metric.ref === 'base')

	let currentData = currentSeries
		? JSON.stringify(currentSeries.values.map(([t, v]) => ({ x: t * 1000, y: parseFloat(v) })))
		: '[]'

	let baseData = baseSeries
		? JSON.stringify(baseSeries.values.map(([t, v]) => ({ x: t * 1000, y: parseFloat(v) })))
		: '[]'

	let annotations = events
		.map((e) => {
			if (e.duration_ms) {
				// Box annotation for events with duration
				let xMax = e.timestamp * 1000 + e.duration_ms
				return `{
			type: 'box',
			xMin: ${e.timestamp * 1000},
			xMax: ${xMax},
			backgroundColor: '#60a5fa20',
			borderColor: '#3b82f6',
			borderWidth: 3,
			label: {
				display: true,
				content: '${escapeJs(e.label)}',
				position: 'start',
				backgroundColor: '#3b82f6',
				color: '#fff',
				font: { size: 12 },
				padding: 6
			}
		}`
			} else {
				// Line annotation for instant events
				return `{
			type: 'line',
			xMin: ${e.timestamp * 1000},
			xMax: ${e.timestamp * 1000},
			borderColor: '#3b82f6',
			borderWidth: 3,
			label: {
				display: true,
				content: '${e.icon}',
				position: 'start',
				backgroundColor: '#3b82f6',
				color: '#fff',
				font: { size: 14 },
				padding: 4
			}
		}`
			}
		})
		.join(',\n')

	return `
(function() {
	const ctx = document.getElementById('chart-${sanitizeId(metricName)}');
	if (!ctx) return;

	new Chart(ctx, {
		type: 'line',
		data: {
			datasets: [
				{
					label: 'Current',
					data: ${currentData},
					borderColor: '#3b82f6',
					backgroundColor: '#3b82f620',
					borderWidth: 2,
					pointRadius: 2,
					pointHoverRadius: 4,
					tension: 0.1,
					fill: true
				},
				${
					baseSeries
						? `{
					label: 'Base',
					data: ${baseData},
					borderColor: '#94a3b8',
					backgroundColor: '#94a3b820',
					borderWidth: 2,
					borderDash: [5, 5],
					pointRadius: 2,
					pointHoverRadius: 4,
					tension: 0.1,
					fill: true
				}`
						: ''
				}
			]
		},
		options: {
			responsive: true,
			maintainAspectRatio: false,
			interaction: {
				mode: 'index',
				intersect: false
			},
			scales: {
				x: {
					type: 'time',
					time: {
						unit: 'minute',
						displayFormats: {
							minute: 'HH:mm'
						}
					},
					title: {
						display: true,
						text: 'Time'
					}
				},
				y: {
					beginAtZero: false,
					title: {
						display: true,
						text: '${escapeJs(metricName)}'
					}
				}
			},
			plugins: {
				legend: {
					display: true,
					position: 'top'
				},
				tooltip: {
					mode: 'index',
					intersect: false
				},
				annotation: {
					annotations: [${annotations}]
				}
			}
		}
	});
})();
`
}

function sanitizeId(str: string): string {
	return str.replace(/[^a-zA-Z0-9]/g, '-')
}

function escapeJs(str: string): string {
	return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/"/g, '\\"').replace(/\n/g, '\\n')
}

function formatTimestamp(timestamp: number): string {
	let date = new Date(timestamp * 1000)
	return date.toISOString().substring(11, 19)
}

function getStyles(): string {
	return `
* {
	margin: 0;
	padding: 0;
	box-sizing: border-box;
}

body {
	font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
	line-height: 1.6;
	color: #24292f;
	background: #ffffff;
	padding: 20px;
}

@media (prefers-color-scheme: dark) {
	body {
		background: #0d1117;
		color: #c9d1d9;
	}
}

header {
	max-width: 1200px;
	margin: 0 auto 40px;
	padding: 30px;
	background: #f6f8fa;
	border-radius: 8px;
	border: 1px solid #d0d7de;
}

@media (prefers-color-scheme: dark) {
	header {
		background: #161b22;
		border-color: #30363d;
	}
}

header h1 {
	font-size: 32px;
	margin-bottom: 15px;
}

.commit-info {
	font-size: 16px;
	margin-bottom: 10px;
	display: flex;
	align-items: center;
	gap: 15px;
	flex-wrap: wrap;
}

.commit {
	padding: 4px 8px;
	border-radius: 4px;
	font-family: 'Courier New', monospace;
	font-size: 14px;
}

.commit.current {
	background: #dff6dd;
	color: #1a7f37;
}

.commit.base {
	background: #ddf4ff;
	color: #0969da;
}

@media (prefers-color-scheme: dark) {
	.commit.current {
		background: #033a16;
		color: #3fb950;
	}
	.commit.base {
		background: #0c2d6b;
		color: #58a6ff;
	}
}

.commit a {
	color: inherit;
	text-decoration: none;
	font-weight: 600;
}

.commit a:hover {
	text-decoration: underline;
}

.vs {
	color: #6e7781;
	font-weight: 600;
}

.meta {
	font-size: 14px;
	color: #6e7781;
	display: flex;
	gap: 15px;
	flex-wrap: wrap;
}

section {
	max-width: 1200px;
	margin: 0 auto 40px;
}

section h2 {
	font-size: 24px;
	margin-bottom: 20px;
	border-bottom: 1px solid #d0d7de;
	padding-bottom: 10px;
}

@media (prefers-color-scheme: dark) {
	section h2 {
		border-color: #30363d;
	}
}

.stats {
	display: grid;
	grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
	gap: 15px;
	margin-bottom: 30px;
}

.stat-card {
	padding: 20px;
	background: #f6f8fa;
	border-radius: 8px;
	border: 2px solid #d0d7de;
	text-align: center;
}

.stat-card.improvements {
	border-color: #1a7f37;
}

.stat-card.regressions {
	border-color: #cf222e;
}

.stat-card.stable {
	border-color: #6e7781;
}

@media (prefers-color-scheme: dark) {
	.stat-card {
		background: #161b22;
		border-color: #30363d;
	}
	.stat-card.improvements {
		border-color: #3fb950;
	}
	.stat-card.regressions {
		border-color: #f85149;
	}
	.stat-card.stable {
		border-color: #8b949e;
	}
}

.stat-value {
	font-size: 36px;
	font-weight: 700;
	margin-bottom: 5px;
}

.stat-label {
	font-size: 14px;
	color: #6e7781;
	font-weight: 500;
}

.comparison-table {
	width: 100%;
	border-collapse: collapse;
	background: #ffffff;
	border: 1px solid #d0d7de;
	border-radius: 8px;
	overflow: hidden;
}

@media (prefers-color-scheme: dark) {
	.comparison-table {
		background: #0d1117;
		border-color: #30363d;
	}
}

.comparison-table th,
.comparison-table td {
	padding: 12px 16px;
	text-align: left;
	border-bottom: 1px solid #d0d7de;
}

@media (prefers-color-scheme: dark) {
	.comparison-table th,
	.comparison-table td {
		border-color: #30363d;
	}
}

.comparison-table th {
	background: #f6f8fa;
	font-weight: 600;
	font-size: 14px;
}

@media (prefers-color-scheme: dark) {
	.comparison-table th {
		background: #161b22;
	}
}

.comparison-table tr:last-child td {
	border-bottom: none;
}

.comparison-table tr.better {
	background: #dff6dd20;
}

.comparison-table tr.worse {
	background: #ffebe920;
}

@media (prefers-color-scheme: dark) {
	.comparison-table tr.better {
		background: #033a1620;
	}
	.comparison-table tr.worse {
		background: #86181d20;
	}
}

.change-cell {
	font-weight: 600;
}

.chart-card {
	margin-bottom: 40px;
	background: #ffffff;
	border: 1px solid #d0d7de;
	border-radius: 8px;
	padding: 20px;
}

@media (prefers-color-scheme: dark) {
	.chart-card {
		background: #0d1117;
		border-color: #30363d;
	}
}

.chart-header {
	margin-bottom: 15px;
}

.chart-header h3 {
	font-size: 18px;
	display: flex;
	align-items: center;
	gap: 10px;
	flex-wrap: wrap;
}

.indicator {
	font-size: 14px;
	padding: 4px 8px;
	border-radius: 4px;
	font-weight: 600;
}

.indicator.better {
	background: #dff6dd;
	color: #1a7f37;
}

.indicator.worse {
	background: #ffebe9;
	color: #cf222e;
}

.indicator.neutral {
	background: #f6f8fa;
	color: #6e7781;
}

@media (prefers-color-scheme: dark) {
	.indicator.better {
		background: #033a16;
		color: #3fb950;
	}
	.indicator.worse {
		background: #86181d;
		color: #ff7b72;
	}
	.indicator.neutral {
		background: #161b22;
		color: #8b949e;
	}
}

.chart-meta {
	font-size: 14px;
	color: #6e7781;
	margin-top: 5px;
}

.chart-container {
	position: relative;
	height: 400px;
}

.events-section {
	max-width: 1200px;
	margin: 40px auto;
}

.events-list {
	display: flex;
	flex-direction: column;
	gap: 10px;
}

.event-item {
	display: flex;
	align-items: center;
	gap: 10px;
	padding: 10px;
	background: #f6f8fa;
	border-radius: 6px;
	border-left: 3px solid #d0d7de;
}

@media (prefers-color-scheme: dark) {
	.event-item {
		background: #161b22;
		border-color: #30363d;
	}
}

.event-marker {
	width: 12px;
	height: 12px;
	border-radius: 50%;
}

.event-icon {
	font-size: 18px;
}

.event-time {
	font-family: 'Courier New', monospace;
	font-size: 14px;
	color: #6e7781;
	min-width: 80px;
}

.event-label {
	font-size: 14px;
	flex: 1;
}

footer {
	max-width: 1200px;
	margin: 60px auto 20px;
	text-align: center;
	color: #6e7781;
	font-size: 14px;
	padding-top: 20px;
	border-top: 1px solid #d0d7de;
}

@media (prefers-color-scheme: dark) {
	footer {
		border-color: #30363d;
	}
}

footer a {
	color: #0969da;
	text-decoration: none;
}

footer a:hover {
	text-decoration: underline;
}

@media (prefers-color-scheme: dark) {
	footer a {
		color: #58a6ff;
	}
}

@media (max-width: 768px) {
	body {
		padding: 10px;
	}

	header h1 {
		font-size: 24px;
	}

	.chart-container {
		height: 300px;
	}

	.stats {
		grid-template-columns: repeat(2, 1fr);
	}
}
`
}
