name: "Generate & Publish Report"
description: "Analyzes metrics, compares results with the base branch, and publishes a detailed report to the pull request."
branding:
  icon: "bar-chart-2"
  color: "blue"

# Required workflow permissions:
# - checks: write (to create GitHub Checks)
# - contents: read (to access repository)
# - pull-requests: write (to create/update PR comments)

inputs:
  github_issue:
    description: "GitHub issue number where the report will be published. If not provided, the action will not create a comment on the PR."
    required: false
  github_token:
    description: "GitHub token used to access the GitHub API for inferring the pull request number."
    required: true
  github_run_id:
    description: "The id of the workflow run where the desired download artifact was uploaded from."
    required: true
  thresholds_yaml:
    description: "Custom thresholds configuration in YAML format (inline). Will be merged with default thresholds."
    required: false
  thresholds_yaml_path:
    description: "Path to a file containing custom thresholds configuration in YAML format. Will be merged with default thresholds."
    required: false

runs:
  using: "node24"
  main: "../dist/report/main.js"
