name: "Generate & Publish Report"
description: "Analyzes metrics, compares results with the base branch, and publishes a detailed report to the pull request."
branding:
  icon: "bar-chart-2"
  color: "blue"

# Required workflow permissions:
# - contents: read (to access repository)
# - pull-requests: write (to create/update PR comments)
# - checks: write (optional, to create GitHub Checks for SLO violations)

inputs:
  github_token:
    description: "GitHub token used to access the GitHub API for inferring the pull request number."
    required: true
  github_run_id:
    description: "The id of the workflow run where the desired download artifact was uploaded from."
    required: true
  thresholds_yaml:
    description: "Custom thresholds configuration (inline YAML string)"
    required: false
  thresholds_yaml_path:
    description: "Path to custom thresholds YAML file"
    required: false

runs:
  using: "node24"
  main: "../dist/report/main.js"
