name: "Generate & Publish Report"
description: "Analyzes metrics, compares results with the base branch, and publishes a detailed report to the pull request."

inputs:
  github_token:
    description: "GitHub token used to access the GitHub API for inferring the pull request number."
    required: true
  github_run_id:
    description: "The id of the workflow run where the desired download artifact was uploaded from."
    required: true

runs:
  using: "node24"
  main: "../dist/report/main.js"
