default:
  step: 5s
  timeout: 30s

metrics:
  - name: read_latency_p50_ms
    unit: ms
    query: 1000 * sum by(ref) (sdk_operation_latency_p50_seconds{operation_type="read"})

  - name: read_latency_p95_ms
    unit: ms
    query: 1000 * sum by(ref) (sdk_operation_latency_p95_seconds{operation_type="read"})

  - name: read_latency_p99_ms
    unit: ms
    query: 1000 * sum by(ref) (sdk_operation_latency_p99_seconds{operation_type="read"})

  - name: write_latency_p50_ms
    unit: ms
    query: 1000 * sum by(ref) (sdk_operation_latency_p50_seconds{operation_type="write"})

  - name: write_latency_p95_ms
    unit: ms
    query: 1000 * sum by(ref) (sdk_operation_latency_p95_seconds{operation_type="write"})

  - name: write_latency_p99_ms
    unit: ms
    query: 1000 * sum by(ref) (sdk_operation_latency_p99_seconds{operation_type="write"})

  - name: read_throughput
    unit: ops/s
    query: sum by(ref) (rate(sdk_operations_total{operation_type="read"}[30s]))

  - name: write_throughput
    unit: ops/s
    query: sum by(ref) (rate(sdk_operations_total{operation_type="write"}[30s]))

  - name: read_attempts
    unit: ops/s
    query: sum by(ref) (rate(sdk_retry_attempts_total{operation_type="read"}[30s]))

  - name: write_attempts
    unit: ops/s
    query: sum by(ref) (rate(sdk_retry_attempts_total{operation_type="write"}[30s]))

  - name: read_availability
    unit: "%"
    query: 100 * clamp_max(sum by (ref) (rate(sdk_operations_success_total{operation_type="read"}[30s])) / sum by (ref) (rate(sdk_operations_total{operation_type="read"}[30s])), 1)
    round: 0.01

  - name: write_availability
    unit: "%"
    query: 100 * clamp_max(sum by (ref) (rate(sdk_operations_success_total{operation_type="write"}[30s])) / sum by (ref) (rate(sdk_operations_total{operation_type="write"}[30s])), 1)
    round: 0.01
