name: Report

on:
  workflow_call:
    inputs:
      github_token:
        required: true
        type: string
      github_run_id:
        required: true
        type: string

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      pages: write
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
      GITHUB_RUN_ID: ${{ inputs.github_run_id }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcairo2-dev \
            libpango1.0-dev \
            libjpeg-dev \
            libgif-dev \
            librsvg2-dev \
            pkg-config

      - name: Install dependencies
        run: |
          cd report
          npm ci

      - name: Build native modules
        run: |
          cd report
          npm rebuild canvas --build-from-source

      - name: Debug inputs
        run: |
          echo "Input github_token exists: ${{ inputs.github_token != '' }}"
          echo "Input github_run_id: ${{ inputs.github_run_id }}"
          echo "Env GITHUB_TOKEN exists: ${GITHUB_TOKEN:+yes}"
          echo "Env GITHUB_RUN_ID: $GITHUB_RUN_ID"

      - name: Generate report
        run: |
          cd report
          npx ts-node src/main.ts

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload charts to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: report/charts
          retention-days: 1

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Update PR comment
        run: |
          cd report
          npx ts-node scripts/update-comment.ts 