name: SLO Report

on:
  workflow_run:
    workflows: ["SLO"]
    types:
      - completed

jobs:
  ydb-slo-action-report:
    runs-on: ubuntu-latest
    name: Publish YDB SLO Report
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Debug inputs
        run: |
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "GitHub Token exists: ${{ secrets.GITHUB_TOKEN != '' }}"

      - name: Publish YDB SLO Report
        uses: ydb-platform/ydb-slo-action/report@charts
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_run_id: ${{ github.event.workflow_run.id }}
