name: ydb-slo-action-test-report

on:
    workflow_run:
        workflows: ['ydb-slo-action-test-init']
        types:
            - completed

jobs:
    test-ydb-slo-action:
        runs-on: ubuntu-latest
        name: Test YDB SLO Action Report
        permissions:
            contents: read
            pull-requests: write
        if: github.event.workflow_run.conclusion == 'success'
        steps:
            - name: Publish YDB SLO Report
              uses: ydb-platform/ydb-slo-action/report@main
