name: ydb-slo-action-test
on:
    workflow_dispatch:
    pull_request_target:
        types: [opened, synchronize, reopened]

jobs:
    test-ydb-slo-action:
        runs-on: ubuntu-latest
        name: YDB SLO Action Test
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout code from PR
              uses: actions/checkout@v4
              with:
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Inititialize YDB SLO Test
              uses: ydb-platform/ydb-slo-action/init@main

            - name: Run chaos testing
              run: echo 'CHAOS 🙈🙈🙈'

            - name: Run user workload
              run: sleep 60

            - name: Report YDB SLO Test results
              uses: ydb-platform/ydb-slo-action/report@main
