name: ydb-slo-action-test-init

on:
    pull_request:
    workflow_dispatch:
        inputs:
            github_pull_request_number:
                required: true

jobs:
    test-ydb-slo-action-init:
        name: Test YDB SLO Action Init
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Inititialize YDB SLO Test
              uses: ydb-platform/ydb-slo-action/init@main
              with:
                  github_pull_request_number: ${{ github.event.inputs.github_pull_request_number }}
                  sdk_name: test

            - name: Run chaos testing
              run: |
                  echo 'Performing chaos testing...'
                  sleep 10

            - name: Run user workload
              run: |
                  echo 'Running user workload...';
                  sleep 10
